### ISSUE TITLE
Assigning simulation parameters

### ISSUE THREAD

**Issue by IOYS-DEV** [FYTalon/pienerf#1]
First of all, thank you for sharing your great research!

I have a few questions about assigning values to a ply file using houdini.
(I have no experience with houdini and am struggling...) 

Can you provide a simple guide on how to assign pin, lam, mu, mass for every vertex position in a plyfile? 

Also, how should I define the parameter assignments for this to be an effective simulation?

**Comment by ShaYito** [comment]
Thank you for reaching out. Regarding using Houdini for preprocessing, I suggest consulting Houdini's official documentation and community forums for in-depth guidance, as our expertise centers on the codebase itself. We're here for any questions related to our project’s code. 
For physical parameters, you can refer to example ply files and default settings of arguments (see README - Parameters).
Appreciate your understanding and support!
